version: "3"
services: 
  node-app: 
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PORT=5000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=student
      - MONGO_INITDB_ROOT_PASSWORD=student123
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=student
      - ME_CONFIG_MONGODB_ADMINPASSWORD=student123
      - ME_CONFIG_MONGODB_SERVER=mongodb
      
volumes:
  mongo-db:
